$ErrorActionPreference = "Stop"

Write-Host "SAT Agentic real Huawei Cloud big data resource inventory" -ForegroundColor Cyan
Write-Host ""
Write-Host "Minimal real E2E:"
Write-Host "  - Business prompt converted into generated/<agent_run_id>/"
Write-Host "  - VPC + private subnet"
Write-Host "  - Restrictive security group"
Write-Host "  - OBS private bucket with raw/silver/gold/release/audit paths"
Write-Host "  - Agent package copied to OBS release/<run_id>/agent_generated/"
Write-Host "  - MRS Spark cluster"
Write-Host "  - MRS Spark smoke job after sample upload"
Write-Host "  - Frontend evidence endpoint reading MRS gold output from OBS"
Write-Host ""
Write-Host "Optional enhancements:"
Write-Host "  - GaussDB(DWS) cluster for SQL serving; enable with -EnableDws"
Write-Host "  - DataArts Studio/Factory; enable with -EnableDataArts after prepaid acceptance"
Write-Host ""
Write-Host "Demo hosting:"
Write-Host "  - Optional ECS + EIP for FastAPI/web front end; enable with -EnableWebEcs"
Write-Host ""
Write-Host "No DuckDB or local database is used as the execution layer."
