param(
    [switch]$StatusOnly,

    [switch]$PersistUserEnv,

    [switch]$WriteLocalEnv,

    [switch]$IncludeDws,

    [switch]$Force,

    [string]$EnvFile = "",

    [string]$Region = "la-south-2",

    [string]$ProjectId = "",

    [string]$NodeKeyPairName = "",

    [string]$AdminCidr = "",

    [string]$ObsBucketName = "",

    [string]$NamePrefix = "",

    [string]$Environment = "",

    [string]$DemoOwner = "",

    [string]$DemoPurpose = "",

    [string]$DemoExpiresAt = ""
)

$ErrorActionPreference = "Stop"

if ($PersistUserEnv -and $WriteLocalEnv) {
    throw "Choose only one target: -PersistUserEnv or -WriteLocalEnv."
}

function ConvertFrom-SecureValue {
    param([Security.SecureString]$SecureValue)
    if ($null -eq $SecureValue) {
        return ""
    }
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecureValue)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
}

function Test-Configured {
    param([string]$Name)
    $value = [Environment]::GetEnvironmentVariable($Name, "Process")
    if (-not $value) { $value = [Environment]::GetEnvironmentVariable($Name, "User") }
    if (-not $value) { $value = [Environment]::GetEnvironmentVariable($Name, "Machine") }
    return [bool]$value
}

function Get-ConfiguredValue {
    param([string]$Name)
    $value = [Environment]::GetEnvironmentVariable($Name, "Process")
    if (-not $value) { $value = [Environment]::GetEnvironmentVariable($Name, "User") }
    if (-not $value) { $value = [Environment]::GetEnvironmentVariable($Name, "Machine") }
    return $value
}

function Read-PlainValue {
    param(
        [string]$Name,
        [string]$Label,
        [string]$DefaultValue = "",
        [bool]$Secret = $false
    )
    $current = Get-ConfiguredValue $Name
    if ($current -and -not $Force) {
        if ($Secret) {
            $secureExisting = Read-Host "$Label is already configured. Press Enter to keep it, or type a replacement" -AsSecureString
            $replacement = ConvertFrom-SecureValue $secureExisting
            if (-not $replacement) {
                return $current
            }
            return $replacement
        }
        $shownDefault = if ($DefaultValue) { $DefaultValue } else { "<keep existing>" }
        $typed = Read-Host "$Label [$shownDefault]"
        if (-not $typed) {
            return $current
        }
        return $typed
    }

    if ($Secret) {
        $secureValue = Read-Host "$Label" -AsSecureString
        return ConvertFrom-SecureValue $secureValue
    }

    $fallback = $DefaultValue
    if (-not $fallback) {
        $fallback = Get-ConfiguredValue $Name
    }
    if ($fallback) {
        $typedValue = Read-Host "$Label [$fallback]"
        if (-not $typedValue) {
            return $fallback
        }
        return $typedValue
    }
    return Read-Host $Label
}

function Set-UserEnvValue {
    param(
        [string]$Name,
        [string]$Value
    )
    if ($null -eq $Value -or $Value -eq "") {
        return
    }
    [Environment]::SetEnvironmentVariable($Name, $Value, "User")
    [Environment]::SetEnvironmentVariable($Name, $Value, "Process")
}

function Write-LocalEnvFile {
    param(
        [string]$Path,
        [hashtable]$Values
    )
    $lines = @(
        "# Local Huawei Cloud credentials for SAT Agentic POC.",
        "# Generated by cloud_real_bigdata/scripts/12_configure_cloud_credentials.ps1.",
        "# This file is ignored by git. Do not paste its values into chat or commit it.",
        ""
    )
    foreach ($name in $Values.Keys | Sort-Object) {
        $value = [string]$Values[$name]
        if ($value -match "[`r`n]") {
            throw "$name contains a newline and cannot be written to .env.local."
        }
        $lines += "$name=$value"
    }
    $lines | Set-Content -LiteralPath $Path -Encoding UTF8
}

function New-CredentialStatus {
    param(
        [string]$ReportDir,
        [bool]$RequireDws
    )
    $required = @(
        "HUAWEICLOUD_ACCESS_KEY",
        "HUAWEICLOUD_SECRET_KEY",
        "HUAWEICLOUD_REGION",
        "HUAWEICLOUD_PROJECT_ID",
        "TF_VAR_mrs_manager_admin_password",
        "TF_VAR_node_key_pair_name"
    )
    if ($RequireDws) {
        $required += "TF_VAR_dws_admin_password"
    }
    $optional = @(
        "TF_VAR_admin_cidr",
        "TF_VAR_obs_bucket_name",
        "TF_VAR_name_prefix",
        "TF_VAR_environment",
        "TF_VAR_demo_owner",
        "TF_VAR_demo_purpose",
        "TF_VAR_demo_expires_at"
    )
    $items = @()
    foreach ($name in ($required + $optional)) {
        $items += [ordered]@{
            name = $name
            configured = Test-Configured $name
            required_for_minimal = $required -contains $name
        }
    }
    $missing = @($items | Where-Object { $_.required_for_minimal -and -not $_.configured })
    $status = if ($missing.Count -eq 0) { "ready" } else { "missing_required" }
    $summary = [ordered]@{
        status = $status
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        mode = if ($RequireDws) { "minimal_plus_dws" } else { "minimal_mrs_obs_ecs_ready" }
        values_printed = $false
        source_policy = "Use env vars, ignored .env.local, or cloud secret service. Do not use skill files, chat, logs, screenshots, cookies, or saved browser sessions."
        missing_required = @($missing.name)
        variables = $items
        next_action = if ($status -eq "ready") {
            ".\cloud_real_bigdata\scripts\10_real_cloud_preflight_plan.ps1 -EnableWebEcs"
        }
        else {
            ".\cloud_real_bigdata\scripts\12_configure_cloud_credentials.ps1 -PersistUserEnv"
        }
    }
    New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null
    $jsonPath = Join-Path $ReportDir "credential_status_latest.json"
    $mdPath = Join-Path $ReportDir "credential_status.md"
    $summary | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding UTF8
    $md = @(
        "# SAT Agentic Credential Status",
        "",
        "- status: $($summary.status)",
        "- mode: $($summary.mode)",
        "- values_printed: false",
        "",
        "## Missing Required",
        ""
    )
    if ($summary.missing_required.Count -eq 0) {
        $md += "- none"
    }
    else {
        foreach ($name in $summary.missing_required) {
            $md += "- $name"
        }
    }
    $md += @(
        "",
        "## Variables",
        "",
        "| name | required | configured |",
        "| --- | --- | --- |"
    )
    foreach ($item in $items) {
        $md += "| $($item.name) | $($item.required_for_minimal) | $($item.configured) |"
    }
    $md += @(
        "",
        "## Next Action",
        "",
        '```powershell',
        $summary.next_action,
        '```',
        "",
        "## Safety Policy",
        "",
        $summary.source_policy
    )
    $md | Set-Content -LiteralPath $mdPath -Encoding UTF8
    return [ordered]@{
        summary = $summary
        json_path = $jsonPath
        markdown_path = $mdPath
    }
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Resolve-Path (Join-Path $scriptDir "..\..")
if (-not $EnvFile) {
    $EnvFile = Join-Path $root ".env.local"
}
$reportDir = Join-Path $root ".cloud_real_bigdata_work\credential_status"

& (Join-Path $scriptDir "00_load_local_env.ps1") -Quiet -EnvFile $EnvFile

if ($PersistUserEnv -or $WriteLocalEnv) {
    Write-Host "Configure Huawei Cloud credentials locally." -ForegroundColor Cyan
    Write-Host "Values are read from this terminal prompt only and are never printed." -ForegroundColor DarkGray
    if ($WriteLocalEnv) {
        Write-Host "Target: $EnvFile" -ForegroundColor Yellow
    }
    elseif ($PersistUserEnv) {
        Write-Host "Target: Windows user environment variables" -ForegroundColor Yellow
    }
    Write-Host ""

    $values = @{}
    $values["HUAWEICLOUD_REGION"] = Read-PlainValue -Name "HUAWEICLOUD_REGION" -Label "Huawei Cloud region" -DefaultValue $Region
    $values["HUAWEICLOUD_PROJECT_ID"] = Read-PlainValue -Name "HUAWEICLOUD_PROJECT_ID" -Label "Huawei Cloud project id" -DefaultValue $ProjectId
    $values["HUAWEICLOUD_ACCESS_KEY"] = Read-PlainValue -Name "HUAWEICLOUD_ACCESS_KEY" -Label "Huawei Cloud access key" -Secret $true
    $values["HUAWEICLOUD_SECRET_KEY"] = Read-PlainValue -Name "HUAWEICLOUD_SECRET_KEY" -Label "Huawei Cloud secret key" -Secret $true
    $values["TF_VAR_mrs_manager_admin_password"] = Read-PlainValue -Name "TF_VAR_mrs_manager_admin_password" -Label "MRS Manager admin password" -Secret $true
    $values["TF_VAR_node_key_pair_name"] = Read-PlainValue -Name "TF_VAR_node_key_pair_name" -Label "Existing Huawei Cloud key pair name" -DefaultValue $NodeKeyPairName

    $adminDefault = if ($AdminCidr) { $AdminCidr } else { Get-ConfiguredValue "TF_VAR_admin_cidr" }
    $values["TF_VAR_admin_cidr"] = Read-PlainValue -Name "TF_VAR_admin_cidr" -Label "Admin CIDR for SSH/HTTP ingress, for example your office/VPN IP as x.x.x.x/32" -DefaultValue $adminDefault

    if ($ObsBucketName -or (Get-ConfiguredValue "TF_VAR_obs_bucket_name") -or $Force) {
        $values["TF_VAR_obs_bucket_name"] = Read-PlainValue -Name "TF_VAR_obs_bucket_name" -Label "Optional OBS bucket name" -DefaultValue $ObsBucketName
    }
    if ($NamePrefix -or (Get-ConfiguredValue "TF_VAR_name_prefix") -or $Force) {
        $values["TF_VAR_name_prefix"] = Read-PlainValue -Name "TF_VAR_name_prefix" -Label "Optional resource name prefix" -DefaultValue $NamePrefix
    }
    if ($Environment -or (Get-ConfiguredValue "TF_VAR_environment") -or $Force) {
        $values["TF_VAR_environment"] = Read-PlainValue -Name "TF_VAR_environment" -Label "Optional environment label" -DefaultValue $Environment
    }
    if ($DemoOwner -or (Get-ConfiguredValue "TF_VAR_demo_owner") -or $Force) {
        $values["TF_VAR_demo_owner"] = Read-PlainValue -Name "TF_VAR_demo_owner" -Label "Demo owner or cleanup owner" -DefaultValue $DemoOwner
    }
    if ($DemoPurpose -or (Get-ConfiguredValue "TF_VAR_demo_purpose") -or $Force) {
        $purposeDefault = if ($DemoPurpose) { $DemoPurpose } else { "sat-agentic-customer-demo" }
        $values["TF_VAR_demo_purpose"] = Read-PlainValue -Name "TF_VAR_demo_purpose" -Label "Demo purpose tag" -DefaultValue $purposeDefault
    }
    if ($DemoExpiresAt -or (Get-ConfiguredValue "TF_VAR_demo_expires_at") -or $Force) {
        $values["TF_VAR_demo_expires_at"] = Read-PlainValue -Name "TF_VAR_demo_expires_at" -Label "Demo expiration UTC timestamp, for example 2026-07-10T18:00:00Z" -DefaultValue $DemoExpiresAt
    }
    if ($IncludeDws) {
        $values["TF_VAR_dws_admin_password"] = Read-PlainValue -Name "TF_VAR_dws_admin_password" -Label "Optional DWS admin password" -Secret $true
    }

    if ($PersistUserEnv) {
        foreach ($name in $values.Keys) {
            Set-UserEnvValue -Name $name -Value $values[$name]
        }
        Write-Host "User environment variables updated. Open a new terminal for other processes to inherit them." -ForegroundColor Green
    }
    elseif ($WriteLocalEnv) {
        Write-LocalEnvFile -Path $EnvFile -Values $values
        & (Join-Path $scriptDir "00_load_local_env.ps1") -Quiet -EnvFile $EnvFile
        Write-Host ".env.local updated. It is ignored by git." -ForegroundColor Green
    }
}

$status = New-CredentialStatus -ReportDir $reportDir -RequireDws ([bool]$IncludeDws)
Write-Host "Credential status: $($status.summary.status)" -ForegroundColor ($(if ($status.summary.status -eq "ready") { "Green" } else { "Yellow" }))
if ($status.summary.missing_required.Count -gt 0) {
    Write-Host "Missing required variables:" -ForegroundColor Yellow
    foreach ($name in $status.summary.missing_required) {
        Write-Host "  - $name" -ForegroundColor Yellow
    }
}
Write-Host "Status JSON: $($status.json_path)"
Write-Host "Status report: $($status.markdown_path)"

if ($StatusOnly -and $status.summary.status -ne "ready") {
    exit 1
}
