param(
    [string]$Region = "la-south-2",

    [string]$CandidateProjectId = "09d63c269e80f5e32f4ec00754ed462d",

    [string]$EnvFile = "",

    [string]$KeyPrefix = "sat-agentic-poc",

    [switch]$CredentialsOnly
)

$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

function Read-EnvPairs {
    param([string]$Path)
    $pairs = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $pairs
    }
    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) { continue }
        $index = $trimmed.IndexOf("=")
        if ($index -le 0) { continue }
        $name = $trimmed.Substring(0, $index).Trim()
        $value = $trimmed.Substring($index + 1)
        if ($name) { $pairs[$name] = $value }
    }
    return $pairs
}

function Write-EnvPairs {
    param(
        [string]$Path,
        [System.Collections.IDictionary]$Pairs
    )
    $lines = @(
        "# Local Huawei Cloud environment for SAT Agentic POC.",
        "# Generated by cloud_real_bigdata/scripts/23_gui_cloud_bootstrap.ps1.",
        "# This file is ignored by git. Never paste its values into chat or commit it.",
        ""
    )
    foreach ($name in $Pairs.Keys | Sort-Object) {
        $value = [string]$Pairs[$name]
        if ($value -match "[`r`n]") {
            throw "$name contains a newline."
        }
        $lines += "$name=$value"
    }
    $lines | Set-Content -LiteralPath $Path -Encoding UTF8
}

function New-MrsPassword {
    param([int]$Length = 20)
    $upper = "ABCDEFGHJKLMNPQRSTUVWXYZ"
    $lower = "abcdefghijkmnopqrstuvwxyz"
    $digits = "23456789"
    $symbols = "!@#%*_-+="
    $all = $upper + $lower + $digits + $symbols
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        function Get-RandomIndex([int]$Maximum) {
            $bytes = New-Object byte[] 4
            $rng.GetBytes($bytes)
            return [int]([BitConverter]::ToUInt32($bytes, 0) % [uint32]$Maximum)
        }
        $characters = New-Object System.Collections.Generic.List[char]
        foreach ($set in @($upper, $lower, $digits, $symbols)) {
            $characters.Add($set[(Get-RandomIndex $set.Length)])
        }
        while ($characters.Count -lt $Length) {
            $characters.Add($all[(Get-RandomIndex $all.Length)])
        }
        for ($i = $characters.Count - 1; $i -gt 0; $i--) {
            $j = Get-RandomIndex ($i + 1)
            $tmp = $characters[$i]
            $characters[$i] = $characters[$j]
            $characters[$j] = $tmp
        }
        return -join $characters
    }
    finally {
        $rng.Dispose()
    }
}

function Protect-LocalSecretFile {
    param([string]$Path)
    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    & icacls $resolvedPath /inheritance:r /grant:r "${identity}:(F)" "*S-1-5-18:(F)" | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to restrict local secret file permissions: $resolvedPath"
    }
}

function New-TextBox {
    param(
        [int]$Top,
        [bool]$Secret = $false
    )
    $textBox = New-Object System.Windows.Forms.TextBox
    $textBox.Location = New-Object System.Drawing.Point(168, $Top)
    $textBox.Size = New-Object System.Drawing.Size(340, 28)
    $textBox.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    if ($Secret) { $textBox.UseSystemPasswordChar = $true }
    return $textBox
}

function New-Label {
    param(
        [string]$Text,
        [int]$Top
    )
    $label = New-Object System.Windows.Forms.Label
    $label.Text = $Text
    $label.Location = New-Object System.Drawing.Point(28, ($Top + 3))
    $label.Size = New-Object System.Drawing.Size(132, 24)
    $label.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    return $label
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Resolve-Path (Join-Path $scriptDir "..\..")
if (-not $EnvFile) { $EnvFile = Join-Path $root ".env.local" }
$workDir = Join-Path $root ".cloud_real_bigdata_work\gui_cloud_bootstrap"
$keyDir = Join-Path $root ".cloud_real_bigdata_work\keys"
$identityReportPath = Join-Path $workDir "cloud_identity_latest.json"
$bootstrapReportPath = Join-Path $workDir "gui_bootstrap_latest.json"
New-Item -ItemType Directory -Force -Path $workDir | Out-Null

$form = New-Object System.Windows.Forms.Form
$form.Text = "Huawei Cloud credentials"
$form.Size = New-Object System.Drawing.Size(560, 360)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.TopMost = $true
$form.Font = New-Object System.Drawing.Font("Segoe UI", 10)

$title = New-Object System.Windows.Forms.Label
$title.Text = "Connect SAT Agentic POC to Huawei Cloud"
$title.Location = New-Object System.Drawing.Point(28, 22)
$title.Size = New-Object System.Drawing.Size(480, 30)
$title.Font = New-Object System.Drawing.Font("Segoe UI Semibold", 13)
$form.Controls.Add($title)

$help = New-Object System.Windows.Forms.Label
$help.Text = "Values stay on this computer. Do not enter your Huawei Cloud login password."
$help.Location = New-Object System.Drawing.Point(28, 56)
$help.Size = New-Object System.Drawing.Size(490, 40)
$help.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($help)

$accountBox = New-TextBox -Top 104
$akBox = New-TextBox -Top 148 -Secret $true
$skBox = New-TextBox -Top 192 -Secret $true
$form.Controls.Add((New-Label -Text "Account / domain" -Top 104))
$form.Controls.Add((New-Label -Text "Access Key (AK)" -Top 148))
$form.Controls.Add((New-Label -Text "Secret Key (SK)" -Top 192))
$form.Controls.Add($accountBox)
$form.Controls.Add($akBox)
$form.Controls.Add($skBox)

$regionLabel = New-Object System.Windows.Forms.Label
$regionLabel.Text = "Region: $Region"
$regionLabel.Location = New-Object System.Drawing.Point(168, 230)
$regionLabel.Size = New-Object System.Drawing.Size(340, 24)
$regionLabel.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($regionLabel)

$connectButton = New-Object System.Windows.Forms.Button
$connectButton.Text = "Connect"
$connectButton.Location = New-Object System.Drawing.Point(332, 268)
$connectButton.Size = New-Object System.Drawing.Size(84, 34)
$connectButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $connectButton
$form.Controls.Add($connectButton)

$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Text = "Cancel"
$cancelButton.Location = New-Object System.Drawing.Point(424, 268)
$cancelButton.Size = New-Object System.Drawing.Size(84, 34)
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton
$form.Controls.Add($cancelButton)

$dialogResult = $form.ShowDialog()
if ($dialogResult -ne [System.Windows.Forms.DialogResult]::OK) {
    [ordered]@{
        status = "cancelled"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        secret_values_printed = $false
        paid_resources_created = $false
    } | ConvertTo-Json | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8
    exit 2
}

$accountName = $accountBox.Text.Trim()
$accessKey = $akBox.Text.Trim()
$secretKey = $skBox.Text.Trim()
$accountBox.Clear()
$akBox.Clear()
$skBox.Clear()
$form.Dispose()

if (-not $accountName -or -not $accessKey -or -not $secretKey) {
    [System.Windows.Forms.MessageBox]::Show(
        "Account/domain, AK, and SK are required.",
        "Missing values",
        "OK",
        "Warning"
    ) | Out-Null
    exit 3
}

$mrsPassword = New-MrsPassword
$env:HUAWEICLOUD_ACCOUNT_NAME = $accountName
$env:HUAWEICLOUD_ACCESS_KEY = $accessKey
$env:HUAWEICLOUD_SECRET_KEY = $secretKey
$env:HUAWEICLOUD_REGION = $Region

try {
    $helper = Join-Path $scriptDir "bootstrap_cloud_identity.py"
    $helperArgs = @(
        "--region", $Region,
        "--candidate-project-id", $CandidateProjectId,
        "--key-dir", $keyDir,
        "--key-prefix", $KeyPrefix,
        "--report", $identityReportPath
    )
    if ($CredentialsOnly) { $helperArgs += "--verify-only" }
    & python $helper @helperArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Huawei Cloud rejected the credentials or project context. Check the local identity report."
    }

    $identityReport = Get-Content -Raw -LiteralPath $identityReportPath -Encoding UTF8 | ConvertFrom-Json
    if ($identityReport.status -ne "ready") {
        throw "Cloud identity bootstrap did not reach ready status."
    }

    $pairs = Read-EnvPairs -Path $EnvFile
    $pairs["HUAWEICLOUD_ACCOUNT_NAME"] = $accountName
    $pairs["HUAWEICLOUD_ACCESS_KEY"] = $accessKey
    $pairs["HUAWEICLOUD_SECRET_KEY"] = $secretKey
    $pairs["HUAWEICLOUD_REGION"] = $Region
    $pairs["HUAWEICLOUD_PROJECT_ID"] = $identityReport.project_id
    $pairs["HW_ACCESS_KEY"] = $accessKey
    $pairs["HW_SECRET_KEY"] = $secretKey
    $pairs["HW_REGION_NAME"] = $Region
    $pairs["HW_PROJECT_ID"] = $identityReport.project_id
    $pairs["TF_VAR_region"] = $Region
    $pairs["TF_VAR_project_id"] = $identityReport.project_id
    foreach ($temporaryName in @(
        "HUAWEICLOUD_SECURITY_TOKEN",
        "HUAWEICLOUD_CREDENTIAL_EXPIRES_AT",
        "HW_SECURITY_TOKEN"
    )) {
        if ($pairs.Contains($temporaryName)) { $pairs.Remove($temporaryName) }
    }
    if (-not $CredentialsOnly) {
        $pairs["TF_VAR_mrs_manager_admin_password"] = $mrsPassword
        $pairs["TF_VAR_node_key_pair_name"] = $identityReport.keypair_name
    }
    Write-EnvPairs -Path $EnvFile -Pairs $pairs
    Protect-LocalSecretFile -Path $EnvFile
    if (-not $CredentialsOnly) {
        Protect-LocalSecretFile -Path $identityReport.private_key_path
    }

    [ordered]@{
        status = "ready"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        region = $Region
        project_id = $identityReport.project_id
        project_id_source = $identityReport.project_id_source
        cloud_keypair_created = [bool]$identityReport.cloud_keypair_created
        keypair_name = if ($CredentialsOnly) { $pairs["TF_VAR_node_key_pair_name"] } else { $identityReport.keypair_name }
        private_key_path = if ($CredentialsOnly) { "" } else { $identityReport.private_key_path }
        mrs_password_generated = (-not $CredentialsOnly)
        credentials_only = [bool]$CredentialsOnly
        env_file = $EnvFile
        secret_values_printed = $false
        paid_resources_created = $false
        next_action = ".\cloud_real_bigdata\scripts\15_pre_apply_readiness.ps1 -EnableWebEcs -RunReadonlyCloudProbe -RunTerraformPreflight"
    } | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8

    $successMessage = if ($CredentialsOnly) {
        "Permanent credentials verified. Existing MRS and ECS settings were preserved. No cloud resources were created."
    }
    else {
        "Credentials verified. Project context, MRS password, and ECS key pair are ready. No paid resources were created."
    }
    [System.Windows.Forms.MessageBox]::Show(
        $successMessage,
        "Huawei Cloud connected",
        "OK",
        "Information"
    ) | Out-Null
    exit 0
}
catch {
    $safeMessage = $_.Exception.Message.Replace($accessKey, "<redacted>").Replace($secretKey, "<redacted>")
    [ordered]@{
        status = "failed"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        secret_values_printed = $false
        paid_resources_created = $false
        error = $safeMessage
        identity_report = $identityReportPath
    } | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8
    [System.Windows.Forms.MessageBox]::Show(
        "$safeMessage`n`nNo paid resources were created.",
        "Huawei Cloud connection failed",
        "OK",
        "Error"
    ) | Out-Null
    exit 1
}
