param(
    [string]$Region = "la-south-2",

    [string]$CandidateProjectId = "09d63c269e80f5e32f4ec00754ed462d",

    [int]$CredentialDurationSeconds = 14400,

    [string]$EnvFile = "",

    [string]$KeyPrefix = "sat-agentic-poc"
)

$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

function Read-EnvPairs {
    param([string]$Path)
    $pairs = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) { return $pairs }
    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) { continue }
        $index = $trimmed.IndexOf("=")
        if ($index -le 0) { continue }
        $pairs[$trimmed.Substring(0, $index).Trim()] = $trimmed.Substring($index + 1)
    }
    return $pairs
}

function Write-EnvPairs {
    param([string]$Path, [System.Collections.IDictionary]$Pairs)
    $lines = @(
        "# Short-lived Huawei Cloud environment for SAT Agentic POC.",
        "# Generated by cloud_real_bigdata/scripts/24_gui_password_bootstrap.ps1.",
        "# The login password and IAM token are never stored.",
        "# This file is ignored by git. Never paste its values into chat or commit it.",
        ""
    )
    foreach ($name in $Pairs.Keys | Sort-Object) {
        $value = [string]$Pairs[$name]
        if ($value -match "[`r`n]") { throw "$name contains a newline." }
        $lines += "$name=$value"
    }
    $lines | Set-Content -LiteralPath $Path -Encoding UTF8
}

function New-MrsPassword {
    param([int]$Length = 20)
    $sets = @(
        "ABCDEFGHJKLMNPQRSTUVWXYZ",
        "abcdefghijkmnopqrstuvwxyz",
        "23456789",
        "!@#%*_-+="
    )
    $all = -join $sets
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $pick = {
            param([string]$Characters)
            $bytes = New-Object byte[] 4
            $rng.GetBytes($bytes)
            $Characters[[int]([BitConverter]::ToUInt32($bytes, 0) % [uint32]$Characters.Length)]
        }
        $characters = New-Object System.Collections.Generic.List[char]
        foreach ($set in $sets) { $characters.Add((& $pick $set)) }
        while ($characters.Count -lt $Length) { $characters.Add((& $pick $all)) }
        for ($i = $characters.Count - 1; $i -gt 0; $i--) {
            $bytes = New-Object byte[] 4
            $rng.GetBytes($bytes)
            $j = [int]([BitConverter]::ToUInt32($bytes, 0) % [uint32]($i + 1))
            $tmp = $characters[$i]
            $characters[$i] = $characters[$j]
            $characters[$j] = $tmp
        }
        return -join $characters
    }
    finally { $rng.Dispose() }
}

function Protect-LocalSecretFile {
    param([string]$Path)
    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
    $identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    & icacls $resolvedPath /inheritance:r /grant:r "${identity}:(F)" "*S-1-5-18:(F)" | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to restrict local secret file permissions: $resolvedPath"
    }
}

function Add-Field {
    param(
        [System.Windows.Forms.Form]$Form,
        [string]$Label,
        [int]$Top,
        [bool]$Secret = $false
    )
    $labelControl = New-Object System.Windows.Forms.Label
    $labelControl.Text = $Label
    $labelControl.Location = New-Object System.Drawing.Point(28, ($Top + 3))
    $labelControl.Size = New-Object System.Drawing.Size(145, 24)
    $textBox = New-Object System.Windows.Forms.TextBox
    $textBox.Location = New-Object System.Drawing.Point(176, $Top)
    $textBox.Size = New-Object System.Drawing.Size(332, 28)
    $textBox.Font = New-Object System.Drawing.Font("Segoe UI", 10)
    if ($Secret) { $textBox.UseSystemPasswordChar = $true }
    $Form.Controls.Add($labelControl)
    $Form.Controls.Add($textBox)
    return $textBox
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Resolve-Path (Join-Path $scriptDir "..\..")
if (-not $EnvFile) { $EnvFile = Join-Path $root ".env.local" }
$workDir = Join-Path $root ".cloud_real_bigdata_work\gui_password_bootstrap"
$keyDir = Join-Path $root ".cloud_real_bigdata_work\keys"
$identityReportPath = Join-Path $workDir "cloud_identity_latest.json"
$bootstrapReportPath = Join-Path $workDir "password_bootstrap_latest.json"
New-Item -ItemType Directory -Force -Path $workDir | Out-Null

$form = New-Object System.Windows.Forms.Form
$form.Text = "Huawei Cloud temporary sign-in"
$form.Size = New-Object System.Drawing.Size(560, 382)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.TopMost = $true
$form.Font = New-Object System.Drawing.Font("Segoe UI", 10)

$title = New-Object System.Windows.Forms.Label
$title.Text = "Create a 4-hour Huawei Cloud session"
$title.Location = New-Object System.Drawing.Point(28, 22)
$title.Size = New-Object System.Drawing.Size(480, 30)
$title.Font = New-Object System.Drawing.Font("Segoe UI Semibold", 13)
$form.Controls.Add($title)

$help = New-Object System.Windows.Forms.Label
$help.Text = "Your password is used once for IAM authentication and is never written to disk."
$help.Location = New-Object System.Drawing.Point(28, 57)
$help.Size = New-Object System.Drawing.Size(490, 40)
$help.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($help)

$accountBox = Add-Field -Form $form -Label "Account / domain" -Top 104
$userBox = Add-Field -Form $form -Label "IAM username" -Top 150
$passwordBox = Add-Field -Form $form -Label "Password" -Top 196 -Secret $true

$userHint = New-Object System.Windows.Forms.Label
$userHint.Text = "Leave IAM username empty when it is the same as the account name."
$userHint.Location = New-Object System.Drawing.Point(176, 230)
$userHint.Size = New-Object System.Drawing.Size(332, 36)
$userHint.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($userHint)

$regionLabel = New-Object System.Windows.Forms.Label
$regionLabel.Text = "Region: $Region | Temporary credentials: 4 hours"
$regionLabel.Location = New-Object System.Drawing.Point(28, 268)
$regionLabel.Size = New-Object System.Drawing.Size(360, 24)
$regionLabel.ForeColor = [System.Drawing.Color]::DimGray
$form.Controls.Add($regionLabel)

$connectButton = New-Object System.Windows.Forms.Button
$connectButton.Text = "Connect"
$connectButton.Location = New-Object System.Drawing.Point(332, 298)
$connectButton.Size = New-Object System.Drawing.Size(84, 34)
$connectButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$form.AcceptButton = $connectButton
$form.Controls.Add($connectButton)

$cancelButton = New-Object System.Windows.Forms.Button
$cancelButton.Text = "Cancel"
$cancelButton.Location = New-Object System.Drawing.Point(424, 298)
$cancelButton.Size = New-Object System.Drawing.Size(84, 34)
$cancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $cancelButton
$form.Controls.Add($cancelButton)

$dialogResult = $form.ShowDialog()
if ($dialogResult -ne [System.Windows.Forms.DialogResult]::OK) {
    [ordered]@{
        status = "cancelled"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        paid_resources_created = $false
    } | ConvertTo-Json | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8
    exit 2
}

$accountName = $accountBox.Text.Trim()
$userName = $userBox.Text.Trim()
$loginPassword = $passwordBox.Text
$accountBox.Clear()
$userBox.Clear()
$passwordBox.Clear()
$form.Dispose()

if (-not $accountName -or -not $loginPassword) {
    [System.Windows.Forms.MessageBox]::Show(
        "Account/domain and password are required.",
        "Missing values",
        "OK",
        "Warning"
    ) | Out-Null
    exit 3
}

try {
    $env:HUAWEICLOUD_LOGIN_PASSWORD = $loginPassword
    $exchangeScript = Join-Path $scriptDir "password_to_temporary_credentials.py"
    $exchangeArguments = @(
        $exchangeScript,
        "--account-name", $accountName,
        "--user-name=$userName",
        "--region", $Region,
        "--candidate-project-id", $CandidateProjectId,
        "--duration-seconds", $CredentialDurationSeconds
    )
    $exchangeRaw = (& python @exchangeArguments | Out-String).Trim()
    $exchangeExitCode = $LASTEXITCODE
    Remove-Item Env:\HUAWEICLOUD_LOGIN_PASSWORD -ErrorAction SilentlyContinue
    $loginPassword = ""
    $exchange = $exchangeRaw | ConvertFrom-Json
    $exchangeRaw = ""
    if ($exchangeExitCode -ne 0 -or $exchange.status -ne "ready") {
        throw ([string]$exchange.error)
    }

    $env:HUAWEICLOUD_ACCESS_KEY = $exchange.access_key
    $env:HUAWEICLOUD_SECRET_KEY = $exchange.secret_key
    $env:HUAWEICLOUD_SECURITY_TOKEN = $exchange.security_token
    $env:HUAWEICLOUD_REGION = $Region
    $env:HUAWEICLOUD_PROJECT_ID = $exchange.project_id
    $env:HW_ACCESS_KEY = $exchange.access_key
    $env:HW_SECRET_KEY = $exchange.secret_key
    $env:HW_SECURITY_TOKEN = $exchange.security_token
    $env:HW_REGION_NAME = $Region
    $env:HW_PROJECT_ID = $exchange.project_id

    $identityHelper = Join-Path $scriptDir "bootstrap_cloud_identity.py"
    & python $identityHelper `
        --region $Region `
        --candidate-project-id $exchange.project_id `
        --key-dir $keyDir `
        --key-prefix $KeyPrefix `
        --report $identityReportPath
    if ($LASTEXITCODE -ne 0) {
        throw "Temporary credentials were issued, but ECS key-pair creation failed."
    }
    $identity = Get-Content -Raw -LiteralPath $identityReportPath -Encoding UTF8 | ConvertFrom-Json
    if ($identity.status -ne "ready") { throw "Cloud identity bootstrap did not reach ready status." }

    $mrsPassword = New-MrsPassword
    $pairs = Read-EnvPairs -Path $EnvFile
    $pairs.Remove("HUAWEICLOUD_LOGIN_PASSWORD")
    $pairs.Remove("OS_PASSWORD")
    $pairs.Remove("HW_USER_PASSWORD")
    $pairs["HUAWEICLOUD_ACCOUNT_NAME"] = $accountName
    $pairs["HUAWEICLOUD_ACCESS_KEY"] = $exchange.access_key
    $pairs["HUAWEICLOUD_SECRET_KEY"] = $exchange.secret_key
    $pairs["HUAWEICLOUD_SECURITY_TOKEN"] = $exchange.security_token
    $pairs["HUAWEICLOUD_CREDENTIAL_EXPIRES_AT"] = $exchange.expires_at
    $pairs["HUAWEICLOUD_REGION"] = $Region
    $pairs["HUAWEICLOUD_PROJECT_ID"] = $exchange.project_id
    $pairs["HW_ACCESS_KEY"] = $exchange.access_key
    $pairs["HW_SECRET_KEY"] = $exchange.secret_key
    $pairs["HW_SECURITY_TOKEN"] = $exchange.security_token
    $pairs["HW_REGION_NAME"] = $Region
    $pairs["HW_PROJECT_ID"] = $exchange.project_id
    $pairs["TF_VAR_region"] = $Region
    $pairs["TF_VAR_project_id"] = $exchange.project_id
    $pairs["TF_VAR_mrs_manager_admin_password"] = $mrsPassword
    $pairs["TF_VAR_node_key_pair_name"] = $identity.keypair_name
    Write-EnvPairs -Path $EnvFile -Pairs $pairs
    Protect-LocalSecretFile -Path $EnvFile
    Protect-LocalSecretFile -Path $identity.private_key_path

    [ordered]@{
        status = "ready"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        region = $Region
        project_id = $exchange.project_id
        project_id_source = $exchange.project_id_source
        credential_type = "temporary_ak_sk_security_token"
        credential_expires_at = $exchange.expires_at
        login_password_persisted = $false
        iam_token_persisted = $false
        cloud_keypair_created = $true
        keypair_name = $identity.keypair_name
        private_key_path = $identity.private_key_path
        mrs_password_generated = $true
        secret_values_printed = $false
        paid_resources_created = $false
    } | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8

    $exchange = $null
    [System.Windows.Forms.MessageBox]::Show(
        "Temporary cloud session, MRS password, and ECS key pair are ready. No paid resources were created.",
        "Huawei Cloud connected",
        "OK",
        "Information"
    ) | Out-Null
    exit 0
}
catch {
    Remove-Item Env:\HUAWEICLOUD_LOGIN_PASSWORD -ErrorAction SilentlyContinue
    $loginPassword = ""
    $safeMessage = $_.Exception.Message
    if (-not $safeMessage) {
        $safeMessage = "The local password bootstrap failed before Huawei Cloud authentication."
    }
    [ordered]@{
        status = "failed"
        generated_at = (Get-Date).ToUniversalTime().ToString("o")
        login_password_persisted = $false
        iam_token_persisted = $false
        secret_values_printed = $false
        paid_resources_created = $false
        error = $safeMessage
    } | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $bootstrapReportPath -Encoding UTF8
    [System.Windows.Forms.MessageBox]::Show(
        "$safeMessage`n`nNo paid resources were created.",
        "Huawei Cloud connection failed",
        "OK",
        "Error"
    ) | Out-Null
    exit 1
}
