#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import psycopg2


CONTRACT_COLUMNS = [
    "id",
    "client_id",
    "product_id",
    "account_id",
    "person_id",
    "external_id",
    "description",
    "status",
    "overdue_at",
    "amount_asset_iso_code",
    "created_at",
    "updated_at",
    "profile_id",
    "cycle_id",
    "first_due_date",
    "effective_date",
    "contracted_amount",
]


def parse_args():
    skill_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Create billing.contracts and COPY generated data into RDS PostgreSQL.")
    parser.add_argument("--csv", required=True, help="contracts.csv generated by generate_contracts_rds_data.py")
    parser.add_argument("--ddl", default=str(skill_root / "assets" / "sql" / "billing_contracts_schema.sql"))
    parser.add_argument("--replace", action="store_true", help="TRUNCATE billing.contracts before loading.")
    parser.add_argument("--summary", default=str(Path.cwd() / "contracts-rds-load-summary.json"))
    return parser.parse_args()


def env(*names: str, default: str | None = None) -> str | None:
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


def connect():
    missing = []
    host = env("RDS_PGHOST", "RDS_HOST", "PGHOST")
    database = env("RDS_PGDATABASE", "PGDATABASE")
    user = env("RDS_PGUSER", "PGUSER")
    password = env("RDS_PGPASSWORD", "PGPASSWORD")
    for name, value in {"RDS_PGHOST/PGHOST": host, "RDS_PGDATABASE/PGDATABASE": database, "RDS_PGUSER/PGUSER": user, "RDS_PGPASSWORD/PGPASSWORD": password}.items():
        if not value:
            missing.append(name)
    if missing:
        raise SystemExit(f"Missing PostgreSQL environment variables: {', '.join(missing)}")
    return psycopg2.connect(
        host=host,
        port=int(env("RDS_PGPORT", "PGPORT", default="5432")),
        dbname=database,
        user=user,
        password=password,
        sslmode=env("RDS_PGSSLMODE", "PGSSLMODE", default="prefer"),
    )


def main():
    args = parse_args()
    csv_path = Path(args.csv).resolve()
    ddl_path = Path(args.ddl).resolve()
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")
    if not ddl_path.exists():
        raise SystemExit(f"DDL not found: {ddl_path}")

    copy_sql = (
        "COPY billing.contracts ("
        + ", ".join(CONTRACT_COLUMNS)
        + ") FROM STDIN WITH (FORMAT CSV, HEADER TRUE, NULL '')"
    )
    with connect() as conn:
        with conn.cursor() as cur:
            cur.execute(ddl_path.read_text(encoding="utf-8"))
            if args.replace:
                cur.execute("TRUNCATE TABLE billing.contracts")
            with csv_path.open("r", encoding="utf-8", newline="") as handle:
                cur.copy_expert(copy_sql, handle)
            cur.execute("SELECT COUNT(*) FROM billing.contracts")
            rows = cur.fetchone()[0]
    summary = {"table": "billing.contracts", "rows_after_load": rows, "csv": str(csv_path)}
    Path(args.summary).write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
