#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
from datetime import date, datetime, timezone
from decimal import Decimal
from pathlib import Path
from uuid import UUID

CONTRACT_COLUMNS = [
    "id",
    "client_id",
    "product_id",
    "account_id",
    "person_id",
    "external_id",
    "description",
    "status",
    "overdue_at",
    "amount_asset_iso_code",
    "created_at",
    "updated_at",
    "profile_id",
    "cycle_id",
    "first_due_date",
    "effective_date",
    "contracted_amount",
]


def parse_args():
    parser = argparse.ArgumentParser(description="Publish billing.contracts CDC events from RDS or JSONL to DMS Kafka.")
    parser.add_argument("--source", choices=["db", "jsonl"], default="db")
    parser.add_argument("--jsonl", help="contracts_cdc.jsonl generated by generate_contracts_rds_data.py")
    parser.add_argument("--topic", default=os.environ.get("DMS_KAFKA_TOPIC", "dockone.billing.contracts"))
    parser.add_argument("--bootstrap-servers", default=os.environ.get("DMS_KAFKA_BOOTSTRAP_SERVERS"))
    parser.add_argument("--security-protocol", default=os.environ.get("DMS_KAFKA_SECURITY_PROTOCOL"))
    parser.add_argument("--sasl-mechanism", default=os.environ.get("DMS_KAFKA_SASL_MECHANISM"))
    parser.add_argument("--sasl-username", default=os.environ.get("DMS_KAFKA_USERNAME"))
    parser.add_argument("--sasl-password", default=os.environ.get("DMS_KAFKA_PASSWORD"))
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--max-messages", type=int)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--summary", default=str(Path.cwd() / "contracts-kafka-publish-summary.json"))
    return parser.parse_args()


def env(*names: str, default: str | None = None) -> str | None:
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return default


def json_value(value):
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.astimezone(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, Decimal):
        return f"{value:.8f}"
    return value


def event_from_row(row: dict) -> dict:
    after = {key: json_value(row[key]) for key in CONTRACT_COLUMNS}
    event_dt = row.get("updated_at") or row["created_at"]
    if isinstance(event_dt, datetime):
        ts_ms = int(event_dt.timestamp() * 1000)
    else:
        ts_ms = int(datetime.now(timezone.utc).timestamp() * 1000)
    return {
        "op": "c",
        "ts_ms": ts_ms,
        "source": {"db": "dockone_exampleapp", "schema": "billing", "table": "contracts"},
        "before": None,
        "after": after,
    }


def db_connection():
    try:
        import psycopg2
    except ImportError as exc:
        raise SystemExit("Missing psycopg2-binary. Install scripts/requirements.txt first.") from exc
    host = env("RDS_PGHOST", "RDS_HOST", "PGHOST")
    database = env("RDS_PGDATABASE", "PGDATABASE")
    user = env("RDS_PGUSER", "PGUSER")
    password = env("RDS_PGPASSWORD", "PGPASSWORD")
    missing = [name for name, value in {"RDS_PGHOST/PGHOST": host, "RDS_PGDATABASE/PGDATABASE": database, "RDS_PGUSER/PGUSER": user, "RDS_PGPASSWORD/PGPASSWORD": password}.items() if not value]
    if missing:
        raise SystemExit(f"Missing PostgreSQL environment variables: {', '.join(missing)}")
    return psycopg2.connect(
        host=host,
        port=int(env("RDS_PGPORT", "PGPORT", default="5432")),
        dbname=database,
        user=user,
        password=password,
        sslmode=env("RDS_PGSSLMODE", "PGSSLMODE", default="prefer"),
    )


def iter_db_events(batch_size: int, max_messages: int | None):
    try:
        from psycopg2.extras import RealDictCursor
    except ImportError as exc:
        raise SystemExit("Missing psycopg2-binary. Install scripts/requirements.txt first.") from exc
    query = (
        "SELECT "
        + ", ".join(CONTRACT_COLUMNS)
        + " FROM billing.contracts ORDER BY COALESCE(updated_at, created_at), id"
    )
    emitted = 0
    with db_connection() as conn:
        with conn.cursor(name="contracts_stream_cursor", cursor_factory=RealDictCursor) as cur:
            cur.itersize = batch_size
            cur.execute(query)
            for row in cur:
                yield event_from_row(row)
                emitted += 1
                if max_messages and emitted >= max_messages:
                    return


def iter_jsonl_events(path: str, max_messages: int | None):
    emitted = 0
    with Path(path).open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                yield json.loads(line)
                emitted += 1
                if max_messages and emitted >= max_messages:
                    return


def build_producer(args):
    try:
        from kafka import KafkaProducer
    except ImportError as exc:
        raise SystemExit("Missing kafka-python. Install scripts/requirements.txt first.") from exc
    if not args.bootstrap_servers:
        raise SystemExit("Missing --bootstrap-servers or DMS_KAFKA_BOOTSTRAP_SERVERS")
    config = {
        "bootstrap_servers": [item.strip() for item in args.bootstrap_servers.split(",") if item.strip()],
        "linger_ms": 50,
        "batch_size": 32768,
        "retries": 5,
        "value_serializer": lambda value: json.dumps(value, separators=(",", ":"), ensure_ascii=False).encode("utf-8"),
        "key_serializer": lambda value: str(value).encode("utf-8"),
    }
    if args.security_protocol:
        config["security_protocol"] = args.security_protocol
    if args.sasl_mechanism:
        config["sasl_mechanism"] = args.sasl_mechanism
    if args.sasl_username:
        config["sasl_plain_username"] = args.sasl_username
    if args.sasl_password:
        config["sasl_plain_password"] = args.sasl_password
    return KafkaProducer(**config)


def main():
    args = parse_args()
    if args.source == "jsonl" and not args.jsonl:
        raise SystemExit("--jsonl is required when --source jsonl")
    events = iter_db_events(args.batch_size, args.max_messages) if args.source == "db" else iter_jsonl_events(args.jsonl, args.max_messages)
    sent = 0
    bytes_out = 0
    producer = None if args.dry_run else build_producer(args)
    try:
        for event in events:
            key = event.get("after", {}).get("id") or event.get("ts_ms")
            payload = json.dumps(event, separators=(",", ":"), ensure_ascii=False)
            bytes_out += len(payload.encode("utf-8")) + 1
            sent += 1
            if producer:
                producer.send(args.topic, key=key, value=event)
            if sent % 1000 == 0:
                print(json.dumps({"published": sent, "bytes": bytes_out, "topic": args.topic}))
        if producer:
            producer.flush()
    finally:
        if producer:
            producer.close()
    summary = {"source": args.source, "topic": args.topic, "messages": sent, "payload_bytes": bytes_out, "dry_run": args.dry_run}
    Path(args.summary).write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
