variable "region" {
  description = "Huawei Cloud region. LA-Santiago is la-south-2."
  type        = string
  default     = "la-south-2"
}

variable "access_key" {
  description = "Huawei Cloud access key."
  type        = string
  sensitive   = true
}

variable "secret_key" {
  description = "Huawei Cloud secret key."
  type        = string
  sensitive   = true
}

variable "domain_name" {
  description = "Huawei Cloud IAM account/domain name."
  type        = string
}

variable "auth_url" {
  description = "Huawei Cloud IAM auth URL."
  type        = string
  default     = "https://iam.myhuaweicloud.com/v3"
}

variable "project_name" {
  description = "Project prefix for all resources."
  type        = string
  default     = "ai-hw-config"
}

variable "availability_zone" {
  description = "Target availability zone. Leave empty to use the first available zone in the region."
  type        = string
  default     = ""
}

variable "vpc_cidr" {
  description = "VPC CIDR."
  type        = string
  default     = "10.88.0.0/16"
}

variable "subnet_cidr" {
  description = "Subnet CIDR."
  type        = string
  default     = "10.88.10.0/24"
}

variable "dns_servers" {
  description = "DNS servers for the subnet."
  type        = list(string)
  default     = ["100.125.1.250", "8.8.8.8"]
}

variable "admin_cidr" {
  description = "CIDR allowed for SSH. Replace with your office IP/CIDR before production apply."
  type        = string
  default     = "0.0.0.0/0"
}

variable "image_id" {
  description = "Optional explicit image ID. Leave empty to query the latest public Ubuntu image in the target region."
  type        = string
  default     = ""
}

variable "image_name" {
  description = "Public image name used when image_id is empty."
  type        = string
  default     = "Ubuntu 22.04 server 64bit"
}

variable "ecs_flavor_id" {
  description = "Optional explicit ECS flavor ID. Leave empty to query the smallest fitting flavor by CPU and memory."
  type        = string
  default     = ""
}

variable "ecs_performance_type" {
  description = "Performance type used by huaweicloud_compute_flavors when ecs_flavor_id is empty."
  type        = string
  default     = "normal"
}

variable "ecs_cpu_core_count" {
  description = "CPU core count used when querying the minimum ECS flavor."
  type        = number
  default     = 1
}

variable "ecs_memory_size" {
  description = "Memory size in GB used when querying the minimum ECS flavor."
  type        = number
  default     = 2
}

variable "admin_password" {
  description = "Temporary ECS administrator password."
  type        = string
  sensitive   = true
}

variable "system_disk_type" {
  description = "System disk type."
  type        = string
  default     = "SSD"
}

variable "system_disk_size_gb" {
  description = "System disk size in GB."
  type        = number
  default     = 40
}

variable "eip_type" {
  description = "EIP type."
  type        = string
  default     = "5_bgp"
}

variable "bandwidth_size_mbit" {
  description = "Public bandwidth in Mbit/s."
  type        = number
  default     = 5
}

variable "site_archive_path" {
  description = "Local tar.gz archive generated by npm run package:ai-site."
  type        = string
  default     = "../../deploy/ai-hardware-config-site.tar.gz"
}

variable "create_rds" {
  description = "Create optional RDS MySQL for future saved scenarios/users. Disabled for minimum cost MVP."
  type        = bool
  default     = false
}

variable "rds_admin_password" {
  description = "RDS administrator password. Required only when create_rds=true."
  type        = string
  sensitive   = true
  default     = ""
}

variable "rds_flavor" {
  description = "Minimum RDS flavor candidate. Confirm availability in la-south-2 before apply."
  type        = string
  default     = "rds.mysql.n1.large.2"
}

variable "rds_volume_type" {
  description = "RDS storage type."
  type        = string
  default     = "CLOUDSSD"
}

variable "rds_volume_size_gb" {
  description = "RDS storage size in GB."
  type        = number
  default     = 40
}

variable "tags" {
  description = "Extra tags."
  type        = map(string)
  default = {
    Environment = "demo"
  }
}
