apiVersion: 1
prune: true
datasources:
  - name: Huawei Big Data Prometheus
    uid: huawei-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
  - name: Huawei Big Data Logs
    uid: huawei-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 5000
